name 'dmlb2000_chefdk'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dmlb2000_chefdk'
long_description 'Installs/Configures dmlb2000_chefdk'
version '0.1.2'

depends 'dmlb2000_users'
depends 'build-essential'
depends 'chef-dk'
depends 'vagrant'
